### ISSUE TITLE
legacy BDV: convert data and send it always as gray16

### ISSUE THREAD

**Issue by xulman** [fiji-hpc/hpc-datastore#24]
[ERROR] Command errored: Create new dataset from XML/HDF5
java.lang.NoSuchMethodError: net.imglib2.img.basictypeaccess.ArrayDataAccessFactory.get(Lnet/imglib2/type/NativeType;)Ljava/lang/Object;
        at bdv.export.ExportScalePyramid$BlockCreator.forType(ExportScalePyramid.java:431)
        at bdv.export.ExportScalePyramid.writeScalePyramid(ExportScalePyramid.java:237)
        at cz.it4i.fiji.datastore.rest_client.WriteSequenceToN5.writeScalePyramid(WriteSequenceToN5.java:249)
        at cz.it4i.fiji.datastore.rest_client.WriteSequenceToN5.writeN5File(WriteSequenceToN5.java:208)
        at cz.it4i.fiji.datastore.ij.ExportSPIMAsN5PlugIn.run(ExportSPIMAsN5PlugIn.java:220)
        at org.scijava.command.CommandModule.run(CommandModule.java:196)
        at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
        at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
        at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
        at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by xulman** [comment]
this looks like mismatch between BDV and imglib2 actually

**Comment by xulman** [comment]
nope, the issue was that I was using G8 (instead of G16)
sooo, renaming the issue to "online convert *->G16"

----
interesting fact: when opening `export.xml` directly from the drive, BDV opens well (even when the data is G8)

**Comment by xulman** [comment]
connected #25

**Comment by xulman** [comment]
the PR #26 should be the solution to this issue
